// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//protoc --go_out=plugins=grpc:. xx.proto
type FindOrderIdRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindOrderIdRequest) Reset()         { *m = FindOrderIdRequest{} }
func (m *FindOrderIdRequest) String() string { return proto.CompactTextString(m) }
func (*FindOrderIdRequest) ProtoMessage()    {}
func (*FindOrderIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *FindOrderIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindOrderIdRequest.Unmarshal(m, b)
}
func (m *FindOrderIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindOrderIdRequest.Marshal(b, m, deterministic)
}
func (m *FindOrderIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindOrderIdRequest.Merge(m, src)
}
func (m *FindOrderIdRequest) XXX_Size() int {
	return xxx_messageInfo_FindOrderIdRequest.Size(m)
}
func (m *FindOrderIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindOrderIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindOrderIdRequest proto.InternalMessageInfo

func (m *FindOrderIdRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type OrderOneResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodName             string   `protobuf:"bytes,2,opt,name=goodName,proto3" json:"goodName,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Num                  int64    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	UserId               int64    `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	CreateTime           string   `protobuf:"bytes,7,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderOneResponse) Reset()         { *m = OrderOneResponse{} }
func (m *OrderOneResponse) String() string { return proto.CompactTextString(m) }
func (*OrderOneResponse) ProtoMessage()    {}
func (*OrderOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *OrderOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderOneResponse.Unmarshal(m, b)
}
func (m *OrderOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderOneResponse.Marshal(b, m, deterministic)
}
func (m *OrderOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderOneResponse.Merge(m, src)
}
func (m *OrderOneResponse) XXX_Size() int {
	return xxx_messageInfo_OrderOneResponse.Size(m)
}
func (m *OrderOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderOneResponse proto.InternalMessageInfo

func (m *OrderOneResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderOneResponse) GetGoodName() string {
	if m != nil {
		return m.GoodName
	}
	return ""
}

func (m *OrderOneResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *OrderOneResponse) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *OrderOneResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OrderOneResponse) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

type BookingGoodsResponse struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingGoodsResponse) Reset()         { *m = BookingGoodsResponse{} }
func (m *BookingGoodsResponse) String() string { return proto.CompactTextString(m) }
func (*BookingGoodsResponse) ProtoMessage()    {}
func (*BookingGoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *BookingGoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingGoodsResponse.Unmarshal(m, b)
}
func (m *BookingGoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingGoodsResponse.Marshal(b, m, deterministic)
}
func (m *BookingGoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingGoodsResponse.Merge(m, src)
}
func (m *BookingGoodsResponse) XXX_Size() int {
	return xxx_messageInfo_BookingGoodsResponse.Size(m)
}
func (m *BookingGoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingGoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookingGoodsResponse proto.InternalMessageInfo

func (m *BookingGoodsResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type BookingGoodsRequest struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	GoodsId              int64    `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsName            string   `protobuf:"bytes,3,opt,name=GoodsName,proto3" json:"GoodsName,omitempty"`
	Num                  int64    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	UserId               int64    `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	Mobile               string   `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingGoodsRequest) Reset()         { *m = BookingGoodsRequest{} }
func (m *BookingGoodsRequest) String() string { return proto.CompactTextString(m) }
func (*BookingGoodsRequest) ProtoMessage()    {}
func (*BookingGoodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *BookingGoodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingGoodsRequest.Unmarshal(m, b)
}
func (m *BookingGoodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingGoodsRequest.Marshal(b, m, deterministic)
}
func (m *BookingGoodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingGoodsRequest.Merge(m, src)
}
func (m *BookingGoodsRequest) XXX_Size() int {
	return xxx_messageInfo_BookingGoodsRequest.Size(m)
}
func (m *BookingGoodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingGoodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookingGoodsRequest proto.InternalMessageInfo

func (m *BookingGoodsRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *BookingGoodsRequest) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *BookingGoodsRequest) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *BookingGoodsRequest) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *BookingGoodsRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BookingGoodsRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func init() {
	proto.RegisterType((*FindOrderIdRequest)(nil), "protos.FindOrderIdRequest")
	proto.RegisterType((*OrderOneResponse)(nil), "protos.OrderOneResponse")
	proto.RegisterType((*BookingGoodsResponse)(nil), "protos.BookingGoodsResponse")
	proto.RegisterType((*BookingGoodsRequest)(nil), "protos.BookingGoodsRequest")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x65, 0x13, 0x4d, 0xdb, 0xa9, 0x48, 0x19, 0x45, 0x96, 0x58, 0xa4, 0xe4, 0xd4, 0x53, 0x10,
	0xfd, 0x03, 0x05, 0x25, 0x17, 0x0b, 0x8b, 0x3f, 0xd0, 0x76, 0x97, 0xb2, 0x68, 0x32, 0x31, 0x9b,
	0xfc, 0x8c, 0x27, 0xaf, 0xfe, 0xa5, 0x64, 0x92, 0xb4, 0x51, 0x2b, 0xd2, 0x53, 0xf2, 0xde, 0x9b,
	0x5d, 0xe6, 0xbd, 0x7d, 0x30, 0xa6, 0x42, 0x9b, 0x22, 0xce, 0x0b, 0x2a, 0x09, 0x03, 0xfe, 0xb8,
	0x28, 0x06, 0x7c, 0xb0, 0x99, 0x5e, 0xd4, 0x52, 0xa2, 0x95, 0x79, 0xab, 0x8c, 0x2b, 0x51, 0xc2,
	0x80, 0x1a, 0x46, 0x8a, 0x99, 0x98, 0x8f, 0x54, 0x07, 0xa3, 0x0f, 0x01, 0x13, 0x1e, 0x5e, 0x64,
	0x46, 0x19, 0x97, 0x53, 0xe6, 0x0c, 0x9e, 0x82, 0x67, 0xbb, 0x49, 0xcf, 0x6a, 0x0c, 0x61, 0xb8,
	0x21, 0xd2, 0x4f, 0xcb, 0xd4, 0x48, 0x8f, 0xd9, 0x2d, 0xc6, 0x0b, 0x08, 0x52, 0x5a, 0xd9, 0x57,
	0x23, 0x7d, 0x56, 0x5a, 0x84, 0x13, 0xf0, 0xb3, 0x2a, 0x95, 0x47, 0x33, 0x31, 0xf7, 0x55, 0xfd,
	0x5b, 0x4f, 0x56, 0x8e, 0x77, 0x38, 0x66, 0xb2, 0x45, 0x78, 0x05, 0xb0, 0x2e, 0xcc, 0xb2, 0x34,
	0xcf, 0x36, 0x35, 0x72, 0xc0, 0xb7, 0xf4, 0x98, 0xe8, 0x1a, 0xce, 0xef, 0x88, 0x5e, 0x6c, 0xb6,
	0x79, 0x24, 0xd2, 0x6e, 0xbb, 0xe5, 0xdf, 0xa6, 0x3e, 0x05, 0x9c, 0x7d, 0x3f, 0xf2, 0x4f, 0x0c,
	0xb5, 0x52, 0x3b, 0x72, 0x89, 0x66, 0x83, 0xbe, 0xea, 0x20, 0x4e, 0x61, 0xc4, 0x77, 0xb0, 0xf9,
	0xc6, 0xe2, 0x8e, 0x38, 0xc0, 0xe5, 0x2e, 0xa7, 0xa0, 0x9f, 0xd3, 0xcd, 0xbb, 0x80, 0x21, 0x3f,
	0x80, 0xca, 0xd7, 0x98, 0xc0, 0x49, 0x7f, 0x6f, 0xbc, 0x6c, 0x5e, 0xd7, 0xc5, 0x7b, 0xdc, 0x84,
	0xd3, 0xfd, 0x62, 0x9b, 0xce, 0x3d, 0x8c, 0x7b, 0x45, 0xc0, 0xb0, 0x1b, 0xfe, 0xdd, 0x8e, 0x50,
	0x76, 0xda, 0xcf, 0x22, 0xac, 0x9a, 0x56, 0xdd, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xc0,
	0xef, 0x79, 0x6b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderRpcClient is the client API for OrderRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderRpcClient interface {
	BookingGoods(ctx context.Context, in *BookingGoodsRequest, opts ...grpc.CallOption) (*BookingGoodsResponse, error)
	FindOrderId(ctx context.Context, in *FindOrderIdRequest, opts ...grpc.CallOption) (*OrderOneResponse, error)
}

type orderRpcClient struct {
	cc *grpc.ClientConn
}

func NewOrderRpcClient(cc *grpc.ClientConn) OrderRpcClient {
	return &orderRpcClient{cc}
}

func (c *orderRpcClient) BookingGoods(ctx context.Context, in *BookingGoodsRequest, opts ...grpc.CallOption) (*BookingGoodsResponse, error) {
	out := new(BookingGoodsResponse)
	err := c.cc.Invoke(ctx, "/protos.OrderRpc/BookingGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderRpcClient) FindOrderId(ctx context.Context, in *FindOrderIdRequest, opts ...grpc.CallOption) (*OrderOneResponse, error) {
	out := new(OrderOneResponse)
	err := c.cc.Invoke(ctx, "/protos.OrderRpc/FindOrderId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderRpcServer is the server API for OrderRpc service.
type OrderRpcServer interface {
	BookingGoods(context.Context, *BookingGoodsRequest) (*BookingGoodsResponse, error)
	FindOrderId(context.Context, *FindOrderIdRequest) (*OrderOneResponse, error)
}

func RegisterOrderRpcServer(s *grpc.Server, srv OrderRpcServer) {
	s.RegisterService(&_OrderRpc_serviceDesc, srv)
}

func _OrderRpc_BookingGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).BookingGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.OrderRpc/BookingGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).BookingGoods(ctx, req.(*BookingGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderRpc_FindOrderId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOrderIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).FindOrderId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.OrderRpc/FindOrderId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).FindOrderId(ctx, req.(*FindOrderIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.OrderRpc",
	HandlerType: (*OrderRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookingGoods",
			Handler:    _OrderRpc_BookingGoods_Handler,
		},
		{
			MethodName: "FindOrderId",
			Handler:    _OrderRpc_FindOrderId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
